extends Node

func globalScopeCall(method: String, args: Array) -> Variant:
	match(method):
		"abs": return abs(args[0])
		"absf": return absf(args[0])
		"absi": return absi(args[0])
		"acos": return acos(args[0])
		"acosh": return acosh(args[0])
		"angle_difference": return angle_difference(args[0], args[1])
		"asin": return asin(args[0])
		"asinh": return asinh(args[0])
		"atan": return atan(args[0])
		"atan2": return atan2(args[0], args[1])
		"atanh": return atanh(args[0])
		"bezier_derivative": return bezier_derivative(args[0], args[1], args[2], args[3], args[4])
		"bezier_interpolate": return bezier_interpolate(args[0], args[1], args[2], args[3], args[4])
		"bytes_to_var": return bytes_to_var(args[0])
		"bytes_to_var_with_objects": return bytes_to_var_with_objects(args[0])
		"ceil": return ceil(args[0])
		"ceilf": return ceilf(args[0])
		"ceili": return ceili(args[0])
		"clamp": return clamp(args[0], args[1], args[2])
		"clampf": return clampf(args[0], args[1], args[2])
		"clampi": return clampi(args[0], args[1], args[2])
		"cos": return cos(args[0])
		"cosh": return cosh(args[0])
		"cubic_interpolate": return cubic_interpolate(args[0], args[1], args[2], args[3], args[4])
		"cubic_interpolate_angle": return cubic_interpolate_angle(args[0], args[1], args[2], 
			args[3], args[4])
		"cubic_interpolate_angle_in_time": return cubic_interpolate_angle_in_time(args[0], args[1], 
			args[2], args[3], args[4], args[5], args[6], args[7])
		"cubic_interpolate_in_time": return cubic_interpolate_in_time(args[0], args[1], args[2], 
			args[3], args[4], args[5], args[6], args[7])
		"db_to_linear": return db_to_linear(args[0])
		"deg_to_rad": return deg_to_rad(args[0])
		"ease": return ease(args[0], args[1])
		"error_string": return error_string(args[0])
		"exp": return exp(args[0])
		"floor": return floor(args[0])
		"floorf": return floorf(args[0])
		"floori": return floori(args[0])
		"fmod": return fmod(args[0], args[1])
		"fposmod": return fposmod(args[0], args[1])
		"hash": return hash(args[0])
		"instance_from_id": return instance_from_id(args[0])
		"inverse_lerp": return inverse_lerp(args[0], args[1], args[2])
		"is_equal_approx": return is_equal_approx(args[0], args[1])
		"is_finite": return is_finite(args[0])
		"is_inf": return is_inf(args[0])
		"is_instance_id_valid": return is_instance_id_valid(args[0])
		"is_instance_valid": return is_instance_valid(args[0])
		"is_nan": return is_nan(args[0])
		"is_same": return is_same(args[0], args[1])
		"is_zero_approx": return is_zero_approx(args[0])
		"lerp": return lerp(args[0], args[1], args[2])
		"lerp_angle": return lerp_angle(args[0], args[1], args[2])
		"lerpf": return lerpf(args[0], args[1], args[2])
		"linear_to_db": return linear_to_db(args[0])
		"log": return log(args[0])
		"max": return max(args)
		"maxf": return maxf(args[0], args[1])
		"maxi": return maxi(args[0], args[1])
		"min": return min(args)
		"minf": return minf(args[0], args[1])
		"mini": return mini(args[0], args[1])
		"move_toward": return move_toward(args[0], args[1], args[2])
		"nearest_po2": return nearest_po2(args[0])
		"pingpong": return pingpong(args[0], args[1])
		"posmod": return posmod(args[0], args[1])
		"pow": return pow(args[0], args[1])
		"print": print(args)
		"print_rich": print_rich(args)
		"print_verbose": print_verbose(args)
		"printerr": printerr(args)
		"printraw": printraw(args)
		"prints": prints(args)
		"printt": printt(args)
		"push_error": push_error(args)
		"push_warning": push_warning(args)
		"rad_to_deg": return rad_to_deg(args[0])
		"rand_from_seed": return rand_from_seed(args[0])
		"randf": return randf()
		"randf_range": return randf_range(args[0], args[1])
		"randfn": return randfn(args[0], args[1])
		"randi": return randi()
		"randi_range": return randi_range(args[0], args[1])
		"randomize": randomize()
		"remap": return remap(args[0], args[1], args[2], args[3], args[4])
		"rid_allocate_id": return rid_allocate_id()
		"rid_from_int64": return rid_from_int64(args[0])
		"rotate_toward": return rotate_toward(args[0], args[1], args[2])
		"round": return round(args[0])
		"roundf": return roundf(args[0])
		"roundi": return roundi(args[0])
		"seed": seed(args[0])
		"sign": return sign(args[0])
		"signf": return signf(args[0])
		"signi": return signi(args[0])
		"sin": return sin(args[0])
		"sinh": return sinh(args[0])
		"smoothstep": return smoothstep(args[0], args[1], args[2])
		"snapped": return snapped(args[0], args[1])
		"snappedf": return snappedf(args[0], args[1])
		"snappedi": return snappedi(args[0], args[1])
		"sqrt": return sqrt(args[0])
		"step_decimals": return step_decimals(args[0])
		"str": return str(args)
		"str_to_var": return str_to_var(args[0])
		"tan": return tan(args[0])
		"tanh": return tanh(args[0])
		"type_convert": return type_convert(args[0], args[1])
		"type_string": return type_string(args[0])
		"typeof": return typeof(args[0])
		"var_to_bytes": return var_to_bytes(args[0])
		"var_to_bytes_with_objects": return var_to_bytes_with_objects(args[0])
		"var_to_str": return var_to_str(args[0])
		"weakref": return weakref(args[0])
		"wrap": return wrap(args[0], args[1], args[2])
		"wrapf": return wrapf(args[0], args[1], args[2])
		"wrapi": return wrapi(args[0], args[1], args[2])
		
		"Color8": return Color8(args[0], args[1], args[2], 255 if(args.size() < 4)else args[3])
		"assert": assert(args[0], args[1])
		"char": return char(args[0])
		"convert": return convert(args[0], args[1])
		"dict_to_inst": return dict_to_inst(args[0])
		"get_stack": return get_stack()
		"inst_to_dict": return inst_to_dict(args[0])
		"is_instance_of": return is_instance_of(args[0], args[1])
		"len": return len(args[0])
		"load": return load(args[0])
		"ord": return ord(args[0])
		#"preload": return null -> requires static string
		"print_debug": print_debug(args)
		"print_stack": print_stack()
		"range": match(args.size()):
			1: return range(args[0])
			2: return range(args[0], args[1])
			3: return range(args[0], args[1], args[2])
		"type_exists": return type_exists(args[0])
		
	return null
